spring.application.name=EngineDataProcessingApplication

# Permitir el uso de hilos virtuales para mejorar el rendimiento en tareas concurrentes
spring.threads.virtual.enabled=true

# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/transacciones
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop


# Configuracion de JPA por lotes.
spring.jpa.properties.hibernate.jdbc.batch_size=50000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
spring.jpa.properties.hibernate.generate_statistics=true

spring.batch.job.enabled=false

# Logging para diagnosticar batch
logging.level.org.springframework.batch=DEBUG
logging.level.com.andres_cmk.EngineDataProcessingApplication=DEBUG

# Configuración de HikariCP para mejorar el rendimiento de la conexión a la base de datos
spring.datasource.hikari.maximum-pool-size=12
spring.datasource.hikari.minimum-idle=6
